;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--prefix-copy-handler
	cua-copy-region
	indent-for-tab-command
	))

(setq mc/cmds-to-run-once
      '(
	cua--prefix-override-handler
	cua-paste
	delete-window
	ignore
	))
